### ISSUE TITLE
추가가 필요한 함수

### ISSUE THREAD

**Issue by djkim1013** [horiJY/kitri94#2]
UserDAO : ServerHandler에서 로그인 성공 시 해당 유저의 남은 시간을 조회하는 함수가 필요합니다.

**Comment by horiJY** [comment]
그렇다면 해당 부분 로직 변경이 필요합니다.

1. 호출 후 받아주는 쪽에서 현재 리턴값인 0 or 1로 결과를 판별하면 안되고
2. project_test/pcuser/UserDAO.java에서 ArrayList<UserVO> 형에 결과를 담아 가져가 blist.get(0).getUserID(), blist.get(0).getRemain 메서드를 통해 값을 꺼내 사용해야 합니다.

**Comment by djkim1013** [comment]
네, 그렇게 적용해보겠습니다.
