### ISSUE TITLE
문제

### ISSUE THREAD

**Issue by RyuJihyun0723** [horiJY/kitri94#6]
1. clientFrame에서 잔여시간 출력 안됨
2. 자리이동 History 안찍힘
3. 시간 충전 History안찍힘, user update 안됨
4. 로그아웃 History 안찍힘
5. 로그인 History 안찍힘
6. 시간구매 창에서 아이디 체크 안됨

**Comment by horiJY** [comment]
1. 확인중

**Comment by horiJY** [comment]
1. messege setRemain 
this.remain = result; 로 되어있었음

**Comment by horiJY** [comment]
2. 확인중

**Comment by horiJY** [comment]
2,3,4,5
outMsg Try 구문 누락 수정완료
