### ISSUE TITLE
시간 충전 후 남은 시간 업데이트

### ISSUE THREAD

**Issue by horiJY** [horiJY/kitri94#9]
시간 충전 후 clientFrame 으로 돌아왔을 때 남은시간 업데이트 구현필요

**Comment by djkim1013** [comment]
ClientFrame : 
https://github.com/horiJY/kitri94/blob/68d9d5bff6a5f63b0d6172324580913173ee5341/src/client/frame/ClientFrame.java#L220-L223

**Comment by RyuJihyun0723** [comment]
clientFrame 로그아웃에 outMsg  remain 없어서 추가했음

**Comment by horiJY** [comment]
#7
